# Generated by Django 5.0 on 2024-01-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_auditlog_row_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='chenges',
            field=models.JSONField(null=True),
        ),
    ]
