# Generated by Django 5.0 on 2024-01-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0009_food_foodimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='foodimage',
            field=models.ImageField(blank=True, null=True, upload_to='foodimage/'),
        ),
    ]
