# Generated by Django 5.0 on 2024-01-11 15:40

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0013_alter_review_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('defman', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='food',
            managers=[
                ('defman', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='review',
            managers=[
                ('defman', django.db.models.manager.Manager()),
            ],
        ),
    ]
