# Generated by Django 5.0 on 2024-01-11 15:40

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offkey', '0003_alter_offkey_discount'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='offkey',
            managers=[
                ('defman', django.db.models.manager.Manager()),
            ],
        ),
    ]
