# Generated by Django 5.0 on 2024-01-11 15:40

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_tag_created_at_tag_deleted_at_tag_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('defman', django.db.models.manager.Manager()),
            ],
        ),
    ]
