# Generated by Django 5.0 on 2024-01-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_rename_coupon_order_offkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
