# Generated by Django 5.0 on 2024-01-11 15:40

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_order_discount_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('defman', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderitem',
            managers=[
                ('defman', django.db.models.manager.Manager()),
            ],
        ),
    ]
